version: '3.8'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php8_app
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      - XDEBUG_MODE=coverage
    user: "1000:1000"
    hostname: php8_app # Ensure this is set